# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci:
    runs-on: self-hosted

    steps:        
    - run: sudo docker stop $(sudo docker ps -a -q)
    - run: sudo docker build -t chat .
    - run: sudo docker run -d -p 80:80 chat
